name: deploy

on:
  push:
    branches:
      - main
      - staging
  pull_request:
  repository_dispatch:
    types:
    - deploy

jobs:
  build-deploy:
    uses: geolexica/ci/.github/workflows/site-deploy.yml@main
      with:
        repository: geolexica/isotc204-glossary
        concepts-path: isotc204-glossary
        production-branch: main
        production-site: https://isotc204.geolexica.org
        staging-branch: staging
        staging-site: https://isotc204-staging.geolexica.org
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        aws-cf-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        aws-s3-bucket-name: ${{ secrets.S3_BUCKET_NAME }}
